### ISSUE TITLE
fix link to paper in README

### ISSUE THREAD

**Issue by sammlapp** [soundclim/anuraset#1]
currently links to github home page

**Comment by jscanass** [comment]
Hi @sammlapp, 

We update the README with the [manuscript](https://arxiv.org/abs/2307.06860) link.  

Cheers, Juan

**Comment by jscanass** [comment]
> Hi @sammlapp,
> 
> We update the README with the [manuscript](https://arxiv.org/abs/2307.06860) link.
> 
> Cheers, Juan
